name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🔧 Manual'
    labels:
      - 'manual'
  - title: '🚨 Breaking'
    labels:
      - 'breaking'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'internal'
      - 'maintenance'
      - 'cleanup'
  - title: '🚦 Tests'
    labels:
      - 'test'
      - 'tests'
  - title: '📦 Dependency updates'
    labels:
      - 'dependencies'
    collapse-after: 15
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  
  $CHANGES

replacers:
  - search: '/naia-(\d+)/gi'
    replace: '[NAIA-$1](https://linear.app/naia/issue/NAIA-$1)'

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '.github/**/*'
      - '/chore\/.+/'
      - '/workflow\/.+/'
      - '/workflows\/.+/'
    branch:
      - '/cleanup\/.+/'
  - label: 'test'
    branch:
      - '/test\/.+/'
      - '/tests\/.+/'
  - label: 'dependencies'
    branch:
      - '/packages\/.+/'
      - '/dependency\/.+/'
      - '/dependencies\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
      - '/bug\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/enhancement\/.+/'
      - '/refactor\/.+/'